version: '3'

services:
  granada-db:
    container_name: granada-db
    restart: always
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-tzkt}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-qwerty}
      POSTGRES_DB: ${POSTGRES_DB:-tzkt_db}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5433:5432

  granada-api:
    container_name: granada-api
    restart: always
    image: bakingbad/tzkt-api:latest
    depends_on:
      - granada-db
    environment:
      ConnectionStrings__DefaultConnection: host=granada-db;port=5432;database=${POSTGRES_DB:-tzkt_db};username=${POSTGRES_USER:-tzkt};password=${POSTGRES_PASSWORD:-qwerty};
      Kestrel__Endpoints__Http__Url: http://0.0.0.0:5000
    ports:
      - 0.0.0.0:5010:5000

  granada-sync:
    container_name: granada-sync
    restart: always
    image: bakingbad/tzkt-sync:latest
    environment:
      ConnectionStrings__DefaultConnection: host=granada-db;port=5432;database=${POSTGRES_DB:-tzkt_db};username=${POSTGRES_USER:-tzkt};password=${POSTGRES_PASSWORD:-qwerty};
      TezosNode__Endpoint: https://rpc.tzkt.io/granadanet/
    depends_on:
      - granada-db

volumes:
  postgres:
