version: '3'

services:
  hangzhou-db:
    container_name: hangzhou-db
    restart: always
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-tzkt}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-qwerty}
      POSTGRES_DB: ${POSTGRES_DB:-tzkt_db}
    volumes:
      - postgres:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 0.0.0.0:5434:5432

  hangzhou-api:
    container_name: hangzhou-api
    restart: always
    image: bakingbad/tzkt-api:latest
    depends_on:
      - hangzhou-db
    environment:
      TZKT_API_KESTREL__ENDPOINTS__HTTP__URL: http://0.0.0.0:5000
      TZKT_API_ConnectionStrings__DefaultConnection: host=hangzhou-db;port=5432;database=${POSTGRES_DB:-tzkt_db};username=${POSTGRES_USER:-tzkt};password=${POSTGRES_PASSWORD:-qwerty};
    expose:
      - 5000
    ports:
      - 0.0.0.0:5020:5000

  hangzhou-sync:
    container_name: hangzhou-sync
    restart: always
    image: bakingbad/tzkt-sync:latest
    environment:
      TZKT_TezosNode__Endpoint: https://rpc.tzkt.io/hangzhou2net/
      TZKT_ConnectionStrings__DefaultConnection: host=hangzhou-db;port=5432;database=${POSTGRES_DB:-tzkt_db};username=${POSTGRES_USER:-tzkt};password=${POSTGRES_PASSWORD:-qwerty};
    depends_on:
      - hangzhou-db

volumes:
  postgres:
